-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE
);

-- Таблица заявок в друзья
CREATE TABLE IF NOT EXISTS friendships (
    userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    friendId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT friendships_pk PRIMARY KEY(userId,friendId)
    );

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
    );

-- Таблица рейтингов
CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255)
    );

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER CHECK (duration >= 0),
    mpa_id INTEGER REFERENCES ratings(id)
    );

-- Таблица соответствия фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres (id) ON DELETE RESTRICT,
    CONSTRAINT film_genre_pk PRIMARY KEY (film_id,genre_id)
    );

-- Таблица соответствия фильмов и лайков
CREATE TABLE IF NOT EXISTS favorite_films (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT favorite_films_pk PRIMARY KEY (film_id,user_id)
);